server:
  port: 8081

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notification_db
    username: notification_user
    password: change_me
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.korteng.notification.model"
        spring.json.value.default.type: ru.korteng.notification.model.TransactionEvent
        spring.json.use.type.headers: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  application:
    name: ${spring.application.name}
    version: 0.0.1-SNAPSHOT