spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    ignore-migration-patterns: "*:pending"
  jpa:
    hibernate:
      ddl-auto: none  # Полностью отключаем Hibernate DDL
    show-sql: true    # Для дебага SQL-запросов
  sql:
    init:
      mode: never     # Отключаем автоинициализацию данных
logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE