apiVersion: v1
kind: Secret
metadata:
  name: finance-secret
  namespace: finance-manager
type: Opaque
data:
  FINANCE_DB_USER: ZmluYW5jZV91c2Vy
  FINANCE_DB_PASSWORD: MzU2MDE1MjU1
  NOTIFICATION_DB_USER: bm90aWZpY2F0aW9uX3VzZXI=
  NOTIFICATION_DB_PASSWORD: MzU2MDE1MjU1